### ISSUE TITLE
Tentei abrir um projeto no intellij mas não aprece o java como generators 

### ISSUE THREAD

**Issue by leticiavianadr** [cami-la/teste-curso-dio-dominando-ides-java-intellij#1]
Tentei abrir um projeto no intellij mas não aprece o java como generators. Eu instalei o programa e segui todos os passos conforme foi ensinado no curso da DIO.
![Captura de tela 2022-09-15 163619](https://user-images.githubusercontent.com/113447869/190493828-aa8f9457-7f18-4e4b-9066-49eaa953696e.png)

**Comment by cami-la** [comment]
Oi, Le. Boa noite. (:

Então, é porque a versão do IntelliJ que você está utilizando é mais atualizada do que a que eu mostro no curso.
Inclusive, criei uma issue para exemplificar: https://github.com/cami-la/curso-dio-dominando-ides-java/issues/19

Se ainda não te ajudou, me retorna que explico de outra forma!

**Comment by leticiavianadr** [comment]
Obrigadaaaaaaa❤️ Problema resolvido!
